version: "2"
services:
  db:
    image: mysql:8.0
    container_name: project_mysql
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
  redis:
    image: redis:alpine
    container_name: project_redis
    ports:
      - 6379:6379
